name: firebase
description: Provides all firebase related features.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_remote_config: ^4.3.8

  dependency_injector:
    path: ../dependency_injector

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2