name: firebase
description: Provides all firebase related features.
publish_to: 'none'

environment:
  sdk: 3.3.4

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  cloud_firestore: ^4.17.0
  firebase_remote_config: ^4.4.2

  dependency_injector:
    path: ../dependency_injector
  log_reporter:
    path: ../log_reporter

dev_dependencies:
  fake_cloud_firestore: ^2.4.9
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2