name: firebase
description: Provides all firebase related features for the app.
publish_to: 'none'

environment:
  sdk: 3.3.4

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^10.10.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  cloud_firestore: ^4.17.3
  firebase_remote_config: ^4.4.5

  dependency_injector:
    path: ../dependency_injector
  log_reporter:
    path: ../log_reporter

dev_dependencies:
  fake_cloud_firestore: ^2.5.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2