name: firebase
description: Provides all firebase related features.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  cloud_firestore: ^4.14.0
  firebase_remote_config: ^4.3.8

  dependency_injector:
    path: ../dependency_injector
  log_reporter:
    path: ../log_reporter

dev_dependencies:
  fake_cloud_firestore: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2