name: firebase
description: Provides all firebase related features for the app.
publish_to: 'none'

environment:
  sdk: 3.4.3

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  cloud_firestore: ^5.0.2
  firebase_remote_config: ^5.0.2

  dependency_injector:
    path: ../dependency_injector
  log_reporter:
    path: ../log_reporter

dev_dependencies:
  fake_cloud_firestore: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2