name: firestore_file_uploader
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.5.0
  http: ^1.2.1
  get_it: ^7.7.0
  googleapis_auth: ^1.6.0
  logger: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.3
  build_runner: ^2.4.9
