name: firestore_file_uploader
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  get_it: ^7.6.4
  googleapis_auth: ^1.4.1
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
  build_runner: ^2.4.6
