name: log_reporter
description: A Flutter package used for generating logs.
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  logger: ^2.0.2+1

  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.3
  mocktail: ^0.3.0
  build_runner: ^2.4.6