name: log_reporter
description: A Flutter package used for generating logs.
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  get_it: ^7.6.4
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^0.3.0
  build_runner: ^2.4.6