name: log_reporter
description: Provides support for generating logs.
publish_to: 'none'

environment:
  sdk: 3.3.3

dependencies:
  logger: ^2.2.0

  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.2