name: app_config
description: "Provides app configuration data"
publish_to: 'none'

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  in_app_review: ^2.0.8
  json_annotation: ^4.8.1
  package_info_plus: ^6.0.0
  url_launcher: ^6.2.6

  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  use_case:
    path: ../use_case

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
