name: app_config
description: "Provides configuration data for the app"
publish_to: 'none'

environment:
  sdk: 3.3.4

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  in_app_review: ^2.0.9
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6

  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  use_case:
    path: ../use_case

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
