include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_renaming_method_parameters

analyzer:
  exclude:
    - bricks/**
  language:
    strict-casts: true
    strict-raw-types: true
