name: dexquiz
description: A quiz on pokemon
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: any
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.8

  app_config:
    path: layers/app_config
  cache:
    path: layers/cache
  core:
    path: layers/core
  dependency_injector:
    path: layers/dependency_injector
  design_system:
    path: layers/design_system
  error_reporter:
    path: layers/error_reporter
  feature_flag:
    path: layers/feature_flag
  firebase:
    path: layers/firebase
  log_reporter:
    path: layers/log_reporter
  remote:
    path: layers/remote
  use_case:
    path: layers/use_case

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  melos: ^4.0.0
  test: ^1.24.9

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
