name: dependency_injector
description: Provides dependency injection for the app
publish_to: 'none'

environment:
  sdk: 3.3.4

dependencies:
  get_it: ^7.7.0
  meta: any

dev_dependencies:
  test: ^1.24.9
  mocktail: ^1.0.2