name: dependency_injector
description: A package for dependency injection.
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.1
  build_runner: ^2.4.6