name: dependency_injector
description: Provides the dependency injection.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  get_it: ^7.6.7
  meta: any

dev_dependencies:
  test: ^1.24.9
  mocktail: ^1.0.2