name: settings
description: "Provides app's setting features"
publish_to: 'none'

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  in_app_review: ^2.0.9

  app_config:
    path: ../../layers/app_config
  core:
    path: ../../layers/core
  dependency_injector:
    path: ../../layers/dependency_injector
  design_system:
    path: ../../layers/design_system
  feature_flag:
    path: ../../layers/feature_flag

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true