name: pokemon
description: "Provides pokemon features"
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  provider: ^6.1.2
  shimmer: ^3.0.0

  app_config:
    path: ../../layers/app_config
  cache:
    path: ../../layers/cache
  core:
    path: ../../layers/core
  dependency_injector:
    path: ../../layers/dependency_injector
  design_system:
    path: ../../layers/design_system
  feature_flag:
    path: ../../layers/feature_flag
  firebase:
    path: ../../layers/firebase
  remote:
    path: ../../layers/remote
  use_case:
    path: ../../layers/use_case

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/pokedex/
    - assets/images/pokemon/background/
    - assets/images/pokemon/type/
    - assets/images/quiz/
    - assets/audio/

flutter_gen:
  output: lib/assets/