name: error_reporter
description: Provides reporting and handling errors.
publish_to: 'none'

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  meta: any

  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  log_reporter:
    path: ../log_reporter
  use_case:
    path: ../use_case

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2