name: error_reporter
description: Provides reporting and handling errors.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  log_reporter:
    path: ../log_reporter
  use_case:
    path: ../use_case

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  build_runner: ^2.4.6