name: use_case
description: Provides base classes for making use cases for the app
publish_to: 'none'

environment:
  sdk: 3.3.4

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5

  dependency_injector:
    path: ../dependency_injector

dev_dependencies:
  test: ^1.24.9
  mocktail: ^1.0.2