name: use_case
description: A Flutter package used for making use cases.
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5
  get_it: ^7.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
  build_runner: ^2.4.6