name: use_case
description: A Flutter package used for making use cases.
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5

  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.3
  mocktail: ^0.3.0
  build_runner: ^2.4.6