name: use_case
description: Provides base classes for making use cases.
publish_to: 'none'

environment:
  sdk: 3.3.3

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5

  dependency_injector:
    path: ../dependency_injector

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.2