name: feature_flag
description: "Provides feature flags for various supported features"
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cache:
    path: ../cache
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  log_reporter:
    path: ../log_reporter
  use_case:
    path: ../use_case

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.2

flutter: