name: feature_flag
description: "Provides feature flags for various supported features"
publish_to: 'none'

environment:
  sdk: 3.3.3
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

  cache:
    path: ../cache
  core:
    path: ../core
  dependency_injector:
    path: ../dependency_injector
  firebase:
    path: ../firebase
  log_reporter:
    path: ../log_reporter
  use_case:
    path: ../use_case

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.3

flutter: