name: remote
description: Provides all remote service for apis.
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1

  dependency_injector:
    path: ../dependency_injector
  log_reporter:
    path: ../log_reporter

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.2