name: design_system
description: "Provide design system for the app"
publish_to: 'none'

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  alchemist: ^0.7.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  meta: ^1.10.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.3.2
  mocktail: ^1.0.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/lottie/
    - assets/gif/
  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/font/Pokemon-Solid.ttf

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true