name: design_system
description: "Provides design system for the app"
publish_to: 'none'

environment:
  sdk: 3.4.3

dependencies:
  flutter:
    sdk: flutter

  adaptive_breakpoints: ^0.1.7
  alchemist: ^0.7.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  meta: any
  recase: ^4.1.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.6.0
  mocktail: ^1.0.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/badge/
    - assets/lottieFiles/
    - assets/gifs/
  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/Pokemon-Solid.ttf

flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true