name: pokedex_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  dio: ^5.4.3+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  fimber: ^0.7.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  http_mock_adapter: ^0.6.1
