name: pokedex_builder
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  args: ^2.4.2
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fimber: ^0.7.0
  get_it: ^7.6.4
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  mocktail: ^1.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  http_mock_adapter: ^0.6.1
