name: core
description: Provides core functionality for the app.
publish_to: 'none'

environment:
  sdk: 3.4.3
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter