name: core
description: Provides core functionality for the app.
publish_to: 'none'

environment:
  sdk: 3.3.4
  flutter: 3.19.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter