name: Static analysis and test app

on:
  workflow_call:

env:
  DART_SDK_VERSION: 3.3.3
  FLUTTER_VERSION: "3.19.5"


jobs:
  analyze_and_test:
    name: Analyse and test the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Get dart dependencies
        run: flutter pub get

      - name: Setup Melos
        run: |
          dart pub global activate melos
          melos bs

      - name: Run code generator
        run: melos gen --no-select

      - name: Statically analyze the code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --exclude-tags golden --coverage --machine > test-results.json

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: test-results.json
          reporter: flutter-json

      - name: Install lcov on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install lcov

      - name: Generate code coverage report from lcov.info
        uses: dethereum/github-actions-report-lcov@v1.0.0
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 40
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ inputs.module_path }}
