name: Build Pokedex

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      FIREBASE_CREDENTIALS:
        required: true

env:
  DART_SDK_VERSION: 3.1.2
  PATH_POKEDEX_BUILDER: ./tools/pokedex_builder
  PATH_POKEDEX_UPLOADER: ./tools/firestore_file_uploader

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  build_pokedex:
    runs-on: ubuntu-latest

    outputs:
      collection_path: ${{ steps.output.outputs.collection_path }}

    defaults:
      run:
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      #- name: Format the Dart code
      #  run: dart format . --set-exit-if-changed

      #- name: Run the code generators
      #  run: dart run build_runner build --delete-conflicting-outputs

      - name: Install dependencies for pokedex_builder
        run: dart pub get

      #- name: Statically analyze the Dart code
      #  run: dart analyze

      #- name: Run the unit tests
      #  run: dart test --file-reporter "json:test-results.json"

      - name: Create firestore collection json File
        run: echo '' > ${{ inputs.flavor }}_pokedex_collection.json

      - name: Fetch, build and create firestore collection json
        run: dart bin/pokedex_builder.dart build --flavor ${{ inputs.flavor }} --path ${{ inputs.flavor }}_pokedex_collection.json

      - name: Print the collection json file
        run: cat ${{ inputs.flavor }}_pokedex_collection.json

      - name: Set the created collection file as output
        id: output
        run: echo "collection_path=${{ inputs.flavor }}_pokedex_collection.json" >> "$GITHUB_OUTPUT"

  upload_pokedex:
    runs-on: ubuntu-latest
    needs: build_pokedex

    defaults:
      run:
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      #- name: Format the Dart code
      #  run: dart format . --set-exit-if-changed

      #- name: Run the code generators
      #  run: dart run build_runner build --delete-conflicting-outputs

      - name: Install dependencies for pokedex_file_uploader
        run: dart pub get

      #- name: Statically analyze the Dart code
      #  run: dart analyze

      #- name: Run the unit tests
      #  run: dart test

      - name: Create credential json File
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > ${{ inputs.flavor }}_service-account.json

      - name: Test ENV
        run: cat ${{ needs.build_pokedex.outputs.collection_path }}

      - name: Upload to firestore
        run: dart bin/firestore_file_uploader.dart upload --flavor ${{ inputs.flavor }} --credentials ${{ inputs.flavor }}_service-account.json --data ${{ needs.build_pokedex.outputs.collection_path }}



