name: Build Pokedex

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      FIREBASE_CREDENTIALS:
        required: true

env:
  DART_SDK_VERSION: 3.1.2
  PATH_POKEDEX_BUILDER: ./tools/pokedex_builder
  PATH_POKEDEX_UPLOADER: ./tools/firestore_file_uploader

jobs:
  test_pokedex_builder:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      #- name: Format the Dart code
      #  run: dart format . --set-exit-if-changed

      #- name: Run the code generators
      #  run: dart run build_runner build --delete-conflicting-outputs

      - name: Install dependencies for pokedex_builder
        run: dart pub get

      #- name: Statically analyze the Dart code
      #  run: dart analyze

      #- name: Run the unit tests
      #  run: dart test --file-reporter "json:test-results.json"

  test_firestore_file_uploader:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      #- name: Format the Dart code
      #  run: dart format . --set-exit-if-changed

      #- name: Run the code generators
      #  run: dart run build_runner build --delete-conflicting-outputs

      - name: Install dependencies for pokedex_file_uploader
        run: dart pub get

      #- name: Statically analyze the Dart code
      #  run: dart analyze

      #- name: Run the unit tests
      #  run: dart test

  build_and_upload_pokedex:
    runs-on: ubuntu-latest
    needs: [test_pokedex_builder, test_firestore_file_uploader]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Install dependencies for pokedex_builder
        run: dart pub get
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

      #- name: Clean the existing pokedex file
      #  run: echo '{}' > ../tools/data/firestore/${{ inputs.flavor }}_pokedex.json

      - name: Fetch, build and create firestore collection json
        run: dart bin/pokedex_builder.dart build --flavor ${{ inputs.flavor }} --path ../tools/data/firestore/${{ inputs.flavor }}_pokedex.json
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

      #- name: Clean the existing service account file
      #  run: echo '{}' > ../tools/data/firebase/service_account.json

      - name: Create credential json File
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > ../tools/data/firebase/service_account.json

      - name: Check the pokedex collection
        run: cat ../tools/data/firestore/${{ inputs.flavor }}_pokedex.json

      - name: Install dependencies for pokedex_file_uploader
        run: dart pub get
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}

      - name: Upload to firestore
        run: dart bin/firestore_file_uploader.dart upload --flavor ${{ inputs.flavor }} --credentials ../tools/data/firebase/service_account.json --data ../tools/data/firestore/${{ inputs.flavor }}_pokedex.json
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}



