name: Build Pokedex

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
    secrets:
      FIREBASE_CREDENTIALS:
        required: true

env:
  DART_SDK_VERSION: 3.3.4
  FLUTTER_VERSION: 3.19.6
  PATH_POKEDEX_BUILDER: ./tools/pokedex_builder
  PATH_POKEDEX_UPLOADER: ./tools/firestore_file_uploader

jobs:
  build_and_upload_pokedex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable



      - name: Setup pokedex builder
        run: |
          dart format lib test --set-exit-if-changed
          dart run build_runner build --delete-conflicting-outputs
          flutter analyze
          flutter test
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

      - name: Fetch, build and create firestore collection json
        run: dart bin/pokedex_builder.dart build --flavor ${{ inputs.flavor }} --path ../data/firestore/pokedex.json
        working-directory: ${{ env.PATH_POKEDEX_BUILDER }}

      - name: Setup firestore uploader
        run: |
          dart format lib test --set-exit-if-changed
          dart run build_runner build --delete-conflicting-outputs
          flutter analyze
          flutter test
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}

      - name: Create credential json File
        run: dart bin/firestore_file_uploader.dart credential_builder --credentials ${{ secrets.FIREBASE_CREDENTIALS }} --path ../data/firebase/service_account.json
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}

      - name: Upload to firestore
        run: dart bin/firestore_file_uploader.dart upload --flavor ${{ inputs.flavor }} --credentials ../data/firebase/service_account.json --data ../data/firestore/pokedex.json
        working-directory: ${{ env.PATH_POKEDEX_UPLOADER }}



