name: Build and Upload all Pokedex every night

on: [push]

jobs:
  build_kanto_pokedex:
    uses: ./.github/workflows/_build_pokedex.yaml
    with:
      flavor: 'kanto'

  upload_kanto_pokedex:
    uses: ./.github/workflows/_upload_pokedex.yaml
    needs: build_kanto_pokedex
    with:
      flavor: 'kanto'
      secrets:
        FIREBASE_CREDENTIALS: ${{ secrets.KANTO_FIREBASE_CREDENTIALS }}
