name: Build and Upload all Pokedex every night

on: [push]

jobs:
  create_kanto_collection_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create firestore collection json File
        run: echo '' > kanto_pokedex_collection.json

      - name: Store json file in workspace
        run: mv kanto_pokedex_collection.json ${{ runner.workspace }}/kanto_pokedex_collection.json

      - name: Print the collection json file
        run: cat  ${{ runner.workspace }}/kanto_pokedex_collection.json

      - name: Set collection path as an output
        id: set_collection_path
        run: echo "::set-output name=collection_path::${{ runner.workspace }}/kanto_pokedex_collection.json"

  build_kanto_pokedex:
    needs: create_kanto_collection_file
    uses: ./.github/workflows/_build_pokedex.yaml
    with:
      flavor: 'kanto'
      collection_path: ${{ needs.create_kanto_collection_file.outputs.collection_path }}

  upload_kanto_pokedex:
    needs: build_kanto_pokedex
    uses: ./.github/workflows/_upload_pokedex.yaml
    with:
      flavor: 'kanto'
      collection_path: ${{ needs.create_kanto_collection_file.outputs.collection_path }}
    secrets:
      FIREBASE_CREDENTIALS: ${{ secrets.KANTO_FIREBASE_CREDENTIALS }}
