name: Build and Upload all Pokedex every night

#on:
#  schedule:
#    - cron: '0 0 * * *'

on:
  push

jobs:
  build_kanto_pokedex:
    uses: ./.github/workflows/_build_upload_pokedex_workflow.yaml
    with:
      flavor: 'kanto'
    secrets:
      FIREBASE_CREDENTIALS: ${{ secrets.KANTO_FIREBASE_CREDENTIALS }}

  build_johto_pokedex:
    uses: ./.github/workflows/_build_upload_pokedex_workflow.yaml
    with:
      flavor: 'johto'
    secrets:
      FIREBASE_CREDENTIALS: ${{ secrets.JOHTO_FIREBASE_CREDENTIALS }}