name: Build and Upload all Pokedex every night

on: [push]

jobs:
  build_kanto_pokedex:
    uses: ./.github/workflows/_build_upload_pokedex_workflow.yaml
    with:
      flavor: 'kanto'
    secrets:
      FIREBASE_CREDENTIALS: ${{ secrets.KANTO_FIREBASE_CREDENTIALS }}