name: Upload release build to playstore

on:
  push:
    tags:
      - '*-release'

concurrency:
  # only one running workflow for a ref (branch, tag)
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  analyze_and_test:
    uses: ./.github/workflows/_analyze_and_test_app.yaml

  build_android_kanto:
    uses: ./.github/workflows/_build_android.yaml
    needs: analyze_and_test
    with:
      flavor: kanto
      target: lib/flavors/kanto/main_kanto.dart
      build_env: prod
      upload_to_github: 'false'
      upload_to_firebase: 'false'
      upload_to_play_store: 'true'
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.KANTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.KANTO_ANDROID_FIREBASE_APP_ID }}
      CREDENTIAL_FILE_CONTENT: ${{ secrets.KANTO_CREDENTIAL_FILE_CONTENT }}
      PLAYSTORE_SERVICE_ACCOUNT_JSON: ${{ secrets.KANTO_PLAYSTORE_SERVICE_ACCOUNT_JSON }}

  build_android_johto:
    uses: ./.github/workflows/_build_android.yaml
    needs: analyze_and_test
    with:
      flavor: johto
      target: lib/flavors/johto/main_johto.dart
      build_env: staging
      upload_to_github: 'false'
      upload_to_firebase: 'false'
      upload_to_play_store: 'true'
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.JOHTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.JOHTO_ANDROID_FIREBASE_APP_ID }}
      CREDENTIAL_FILE_CONTENT: ${{ secrets.JOHTO_CREDENTIAL_FILE_CONTENT }}
      PLAYSTORE_SERVICE_ACCOUNT_JSON: ${{ secrets.JOHTO_PLAYSTORE_SERVICE_ACCOUNT_JSON }}