name: Run static code analysis and unit test for settings feature module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - features/settings/**

#on:
#  push

permissions:
  checks: write

jobs:
  feature_settings:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './features/settings'
      should_run_golden_test: 'false'

