name: Run static code analysis and unit test for design system module

#on:
#  push:
#    paths:
#      - layers/design_system/**

on:
  push

permissions:
  checks: write

jobs:
  layer_design_system:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/design_system'

