name: Analyze and test use case layer module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layers/use_case/**'
      - '.github/workflows/layer_use_case.yaml'

permissions:
  checks: write

jobs:
  layer_use_case:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/use_case'
      should_run_golden_test: 'false'
      has_build_runner: 'false'
      have_dependent_build_runner: 'false'