name: Run static code analysis and unit test for remote module

on:
  push:
    branches:
      - staging
    paths:
      - layers/remote/**

#on:
#  push

permissions:
  checks: write

jobs:
  layer_remote:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/remote'
      should_run_golden_test: 'false'

