name: Run static code analysis and unit test for dependency_injector module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layers/dependency_injector/**'
      - '.github/workflows/layer_dependency_injector.yaml'

permissions:
  checks: write

jobs:
  layer_dependency_injector:
    uses: ./.github/workflows/_analyze_and_test_dart_module.yaml
    with:
      module_path: './layers/dependency_injector'
      has_build_runner: 'false'
      have_dependent_build_runner: 'false'

