name: Run static code analysis and unit test for firebase module

on:
  push:
    paths:
      - layers/firebase/**

permissions:
  checks: write

jobs:
  test-and-analyze_firebase_layer:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/firebase'

