name: Run static code analysis and unit test for remote module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - staging
    paths:
      - layers/remote/**
    tags:
      - '*'

#on:
#  push

permissions:
  checks: write

jobs:
  layer_remote:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/remote'
      should_run_golden_test: 'false'
      has_build_runner: 'false'
      have_dependent_build_runner: 'false'

