name: Run static code analysis and unit test for app config module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layers/app_config/**'
      - '.github/workflows/layer_app_config.yaml'

permissions:
  checks: write

jobs:
  layer_app_config:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/app_config'
      should_run_golden_test: 'false'
      has_build_runner: 'true'
      have_dependent_build_runner: 'false'

