name: Run static code analysis and unit test for firebase module

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layers/firebase/**'
      - '.github/workflows/layer_firebase.yaml'

permissions:
  checks: write

jobs:
  layer_firebase:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/firebase'
      should_run_golden_test: 'false'
      has_build_runner: 'false'
      have_dependent_build_runner: 'false'

