name: Run static code analysis and unit test for log reporter module

on:
  push:
    paths:
      - layers/log_reporter/**

permissions:
  checks: write

jobs:
  test-and-analyze:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './layers/log_reporter'

