name: Test, build and upload artefacts on every push

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  analyze_and_test:
    uses: ./.github/workflows/_analyze_and_test_app.yaml

  build_android_kanto:
    uses: ./.github/workflows/_build_android.yaml
    needs: analyze_and_test
    with:
      flavor: kanto
      target: lib/flavors/kanto/main_kanto.dart
      upload_to_github: 'true'
      upload_to_firebase: 'false'
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.KANTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.KANTO_ANDROID_FIREBASE_APP_ID }}
      CREDENTIAL_FILE_CONTENT: ${{ secrets.KANTO_CREDENTIAL_FILE_CONTENT }}

  build_android_johto:
    uses: ./.github/workflows/_build_android.yaml
    needs: analyze_and_test
    with:
      flavor: johto
      target: lib/flavors/johto/main_johto.dart
      upload_to_github: 'true'
      upload_to_firebase: 'false'
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.JOHTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      FIREBASE_APP_ID: ${{ secrets.JOHTO_ANDROID_FIREBASE_APP_ID }}
      CREDENTIAL_FILE_CONTENT: ${{ secrets.JOHTO_CREDENTIAL_FILE_CONTENT }}

