name: Test, build and upload artefacts on every push

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build_android_johto:
    uses: ./.github/workflows/_build_android.yaml
    with:
      flavor: johto
      target: lib/flavors/johto/main_johto.dart
    secrets:
      SIGNING_KEYSTORE: ${{ secrets.JOHTO_KEYSTORE }}
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

