name: Test, build and upload artefacts on every push

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  analyze_and_test:
    uses: ./.github/workflows/_analyze_and_test_app.yaml


