name: Analyse and test Storybook

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'tools/storybook/**'
      - '.github/workflows/storybook_test_and_analyze.yaml'


jobs:
  analyze-and-test-storybook:
    uses: ./.github/workflows/_analyze_test_and_deploy_storybook.yaml
    with:
      should_deploy: 'false'
