name: Analyse and test Storybook

#on:
#  push:
#    paths:
#      - 'tools/storybook/**'

on:
  push

permissions:
  contents: write

jobs:
  layer_core:
    uses: ./.github/workflows/_analyze_and_test_flutter_module.yaml
    with:
      module_path: './tools/storybook'
      should_run_golden_test: 'false'